#!/bin/bash

# Adding ROM2109 ROBOTS to .gazebo/model
if [[ -e ~/.gazebo/models ]]
then
	echo "models Directory exists."
	rm -rf ~/.gazebo/models/rom2109*
	rm -rf ~/.gazebo/models/rom_maze*
else
	mkdir -p ~/.gazebo/models
fi
cp -r ./models/* ~/.gazebo/models
echo "models Copy finished!"

# Modifying urdf.urdf
echo "Modifying file paths in urdf.urdf "
read -p "Enter ROS2 WORKSPACE FOLDER eg.(/home/your_username/path_to_ros2_workspace) :" ros2_ws_path
name=$HOME

str1="$HOME/.gazebo"
sed -i "s|/home/mr_robot/.gazebo|$str1|" ./rom2109_description/urdf/urdf.urdf
str2="<parameters>$ros2_ws_path"
sed -i "s|<parameters>/home/mr_robot/ros2/developer_ws|$str2|" ./rom2109_description/urdf/yoururdf.urdf

# Remove cafe.world
rm ./rom2109_gazebo/worlds/cafe.world
echo "Deleting rom2109_gazebo/worlds/cafe.world"
echo "OK"

echo "export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp" >> ~/.bashrc
echo "Exporting rmw_cyclonedds_cpp : OK "

git clone git@github.com:ROM-robotics/tmux_install.git
#cd tumx_install
#./start.sh
echo "Cloning ROM-robotics/tmux_install.git"

cp ./.tmuxinator.yml ./autostart.sh $HOME/
echo "Copying .tmuxinator.yaml, autostart.sh to $HOME "
